backend:
  name: git-gateway
  branch: master

#publish_mode: editorial_workflow

media_folder: "content/images"

collections:
  - name: "projects"
    label: "Project"
    folder: "content/projects"
    slug: "{{linkSlug}}"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Link Slug", name: "linkSlug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "GitHub Link", name: "githubLink", widget: "string" }
      - { label: "Website Link", name: "websiteLink", widget: "string", required: false }
      - { label: "Collaborators", name: "collaborators", widget: "string", required: false }
