backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "content/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    slug: "{{slug}}"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "text" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "GitHub Link", name: "githubLink", widget: "text" }